### ISSUE TITLE
Validation rules for full name in verifying account.

### ISSUE THREAD

**Issue by JacksonTai** [JacksonTai/Ex-Ledge#38]
**Problem**
The validation rules should allow the user to enter one space in between their full name.

**Note:** 
Everyone is welcomed to address this issue, it's about the validation rules in the `verifyUser` method of user model class.

**Comment by jyyyyylim** [comment]
is this whats needed? multiple spacing in names shouldnt be an issue since its already prefiltered by ctype_alpha()

**Comment by JacksonTai** [comment]
> is this whats needed? multiple spacing in names shouldnt be an issue since its already prefiltered by ctype_alpha()

Sorry for not mentioning it clearly, we might need to avoid something like this.
![image](https://user-images.githubusercontent.com/74141823/159101043-c6ed707b-a878-4523-8e5e-38c8d0211e08.png)

**Comment by jyyyyylim** [comment]
ok, unusual requirement but this should be whats needed now

**Comment by JacksonTai** [comment]
> ok, unusual requirement but this should be whats needed now

At least we don't want to store this kind of full name in our database
![image](https://user-images.githubusercontent.com/74141823/159104838-52afb4f9-486f-4525-9dea-aa7241ef7e6c.png)

**Comment by JacksonTai** [comment]
It still doesn't seems to be fixed.

![image](https://user-images.githubusercontent.com/74141823/159104869-ec62b412-c91c-4c17-8a00-44558866ce52.png)

**Comment by EHeng17** [comment]
How about, a code that replaces multiple consecutive spaces into one single space?
https://stackoverflow.com/questions/2368539/php-replacing-multiple-spaces-with-a-single-space
I hope this link helps, if this error still occur, I will find for a better solution

**Comment by JacksonTai** [comment]
> How about, a code that replaces multiple consecutive spaces into one single space? https://stackoverflow.com/questions/2368539/php-replacing-multiple-spaces-with-a-single-space I hope this link helps, if this error still occur, I will find for a better solution

Yes, this is one of the approach.

**Comment by jyyyyylim** [comment]
> At least we don't want to store this kind of full name in our database ![image](https://user-images.githubusercontent.com/74141823/159104838-52afb4f9-486f-4525-9dea-aa7241ef7e6c.png)

thanks for clarifying, understood whats needed now.

**Comment by JacksonTai** [comment]
Finally, thanks a lot
